### ISSUE TITLE
Footnotes and References

### ISSUE THREAD

**Issue by Hipomenes** [mfenner/jekyll-pandoc#13]
Hello there, I wonder if this project is still maintained... I just installed jekyll-pandoc successfully, using Pandoc 2.1 and modifying the _config.yam accordingly. I then build the site all all seems fine, but footnotes nor citepro references are not rendering at all in html.

What do you think might be the problem? 

Best!
d

**Comment by i2000s** [comment]
Have you set up the bibtex source address correctly in your configure file? Like
```
markdown: Pandoc
pandoc:
  extensions:
    - bibliography: bibliography.bib
```
