### ISSUE TITLE
markdown+extension

### ISSUE THREAD

**Issue by karelv** [mfenner/jekyll-pandoc#8]
How should I configure the `--from` option of pandoc?
I want to enable some extension like `autolink_bare_uris`

in the command line I would do:
`pandoc --from=markdown+autolink_bare_uris`

**Comment by karelv** [comment]
I works like this:
```yml
pandoc:
  extensions:
    - from: markdown+autolink_bare_uris
```
